import type { Prisma } from "@prisma/client";

import type { SiteAuditResult } from "@/lib/audit/site";
import type { BrandDto, BrandWriteInput } from "@/lib/brand/types";

function detectedName(title: string | null, finalUrl: string): string {
  const titleName = title?.split(/\s+[|·—–-]\s+/)[0]?.trim();
  if (titleName && titleName.length >= 2) return titleName.slice(0, 120);
  const hostname = new URL(finalUrl).hostname.replace(/^www\./, "");
  const label = hostname.split(".")[0] || hostname;
  return label.charAt(0).toUpperCase() + label.slice(1);
}

/**
 * Build the Brand write generated by an audit. A re-audit refreshes only source
 * evidence and the canonical URL; every user-editable field is preserved exactly,
 * including intentional nulls and empty lists.
 */
export function mergeSiteAuditIntoBrand(
  existing: BrandDto | null,
  audit: SiteAuditResult,
  auditedAt = new Date(),
): BrandWriteInput {
  const snapshot = JSON.parse(JSON.stringify(audit)) as Prisma.InputJsonValue;

  if (existing) {
    return {
      name: existing.name,
      websiteUrl: audit.finalUrl,
      summary: existing.summary,
      audience: existing.audience,
      voice: existing.voice,
      offers: existing.offers,
      competitors: existing.competitors,
      proofPoints: existing.proofPoints,
      visualStyle: existing.visualStyle,
      locale: existing.locale,
      timezone: existing.timezone,
      currency: existing.currency,
      auditSnapshot: snapshot,
      auditedAt,
    };
  }

  return {
    name: detectedName(audit.title, audit.finalUrl),
    websiteUrl: audit.finalUrl,
    summary: audit.metaDescription,
    audience: [],
    voice: [],
    offers: audit.headings.h2.slice(0, 8),
    competitors: [],
    proofPoints: [],
    visualStyle: [],
    locale: audit.lang || "en",
    timezone: "UTC",
    currency: "EUR",
    auditSnapshot: snapshot,
    auditedAt,
  };
}
