import { prisma } from "@/lib/db";

export const WORKSPACE_EXPORT_SCHEMA_VERSION = 1 as const;

/**
 * Build a tenant-scoped portability export. Every relation uses an explicit
 * select so encrypted OAuth credentials and private Blob storage keys can
 * never be added to the response by a future broad include.
 */
export async function buildWorkspaceExport(workspaceId: string) {
  const workspace = await prisma.workspace.findUnique({
    where: { id: workspaceId },
    select: {
      id: true,
      name: true,
      slug: true,
      timezone: true,
      locale: true,
      currency: true,
      createdAt: true,
      updatedAt: true,
      memberships: {
        select: {
          id: true,
          clerkUserId: true,
          role: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      connections: {
        select: {
          id: true,
          platform: true,
          externalAccountId: true,
          displayName: true,
          status: true,
          scopes: true,
          expiresAt: true,
          currency: true,
          timezone: true,
          lastSyncAt: true,
          lastSuccessfulSyncAt: true,
          lastErrorCode: true,
          lastErrorMessage: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      syncAttempts: {
        select: {
          id: true,
          connectionId: true,
          trigger: true,
          status: true,
          requestedFrom: true,
          requestedTo: true,
          observedFrom: true,
          observedTo: true,
          currency: true,
          timezone: true,
          metricsStatus: true,
          campaignsStatus: true,
          adsStatus: true,
          phaseDetails: true,
          errorCode: true,
          errorMessage: true,
          startedAt: true,
          completedAt: true,
        },
      },
      metricFacts: {
        select: {
          id: true,
          connectionId: true,
          platform: true,
          date: true,
          campaignExternalId: true,
          campaignName: true,
          metric: true,
          value: true,
          currency: true,
          staleAt: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      campaigns: {
        select: {
          id: true,
          connectionId: true,
          platform: true,
          providerExternalId: true,
          name: true,
          status: true,
          objective: true,
          budget: true,
          budgetType: true,
          currency: true,
          staleAt: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      ads: {
        select: {
          id: true,
          connectionId: true,
          platform: true,
          providerExternalId: true,
          campaignExternalId: true,
          campaignName: true,
          adsetName: true,
          name: true,
          status: true,
          creativeType: true,
          thumbnailUrl: true,
          title: true,
          body: true,
          callToAction: true,
          linkUrl: true,
          spend: true,
          impressions: true,
          clicks: true,
          conversions: true,
          currency: true,
          metricsFrom: true,
          metricsTo: true,
          staleAt: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      paidCampaignDrafts: {
        select: {
          id: true,
          connectionId: true,
          platform: true,
          accountId: true,
          accountName: true,
          source: true,
          template: true,
          state: true,
          snapshot: true,
          snapshotHash: true,
          version: true,
          createdBy: true,
          updatedBy: true,
          readyAt: true,
          createdAt: true,
          updatedAt: true,
          mutations: {
            select: {
              id: true,
              kind: true,
              resultVersion: true,
              resultState: true,
              actorId: true,
              createdAt: true,
            },
          },
          approvals: {
            select: {
              id: true,
              kind: true,
              platform: true,
              connectionId: true,
              accountId: true,
              snapshotVersion: true,
              snapshotHash: true,
              approvedBy: true,
              approvedAt: true,
            },
          },
          attempts: {
            select: {
              id: true,
              approvalId: true,
              operation: true,
              snapshotVersion: true,
              snapshotHash: true,
              status: true,
              capabilityReason: true,
              providerOutcome: true,
              actorId: true,
              attemptedAt: true,
            },
          },
        },
      },
      agentRuns: {
        select: {
          id: true,
          brandId: true,
          conversationId: true,
          mode: true,
          goal: true,
          planKey: true,
          target: true,
          status: true,
          dispatchStatus: true,
          dispatchErrorCode: true,
          limits: true,
          stepsUsed: true,
          toolCallsUsed: true,
          modelTurnsUsed: true,
          webReadsUsed: true,
          creditsUsed: true,
          attempt: true,
          version: true,
          failureCode: true,
          failureMessage: true,
          deadlineAt: true,
          cancelRequestedAt: true,
          startedAt: true,
          completedAt: true,
          createdBy: true,
          createdAt: true,
          updatedAt: true,
          steps: {
            select: {
              id: true,
              ordinal: true,
              attempt: true,
              toolName: true,
              risk: true,
              status: true,
              approvalBinding: true,
              outputObjectType: true,
              outputObjectId: true,
              outputObjectVersion: true,
              outputSnapshotHash: true,
              errorCode: true,
              errorMessage: true,
              startedAt: true,
              completedAt: true,
              createdAt: true,
            },
          },
          events: {
            select: {
              id: true,
              sequence: true,
              type: true,
              label: true,
              detail: true,
              objectType: true,
              objectId: true,
              evidenceIds: true,
              createdAt: true,
            },
          },
          approvals: {
            select: {
              id: true,
              stepId: true,
              decision: true,
              kind: true,
              objectType: true,
              objectId: true,
              objectVersion: true,
              snapshotHash: true,
              accountId: true,
              expiresAt: true,
              decidedBy: true,
              decidedAt: true,
            },
          },
          commands: {
            select: {
              id: true,
              kind: true,
              resultStatus: true,
              resultVersion: true,
              actorId: true,
              createdAt: true,
            },
          },
        },
      },
      subscription: {
        select: {
          id: true,
          stripeCustomerId: true,
          stripeSubId: true,
          stripePriceId: true,
          billingInterval: true,
          plan: true,
          status: true,
          currentPeriodStart: true,
          currentPeriodEnd: true,
          cancelAtPeriodEnd: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      usageEvents: {
        select: {
          id: true,
          kind: true,
          credits: true,
          model: true,
          status: true,
          periodStart: true,
          periodEnd: true,
          reservedAt: true,
          committedAt: true,
          releasedAt: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      billingEvents: {
        select: {
          id: true,
          stripeEventId: true,
          type: true,
          stripeCreatedAt: true,
          processedAt: true,
          createdAt: true,
        },
      },
      actions: {
        select: {
          id: true,
          platform: true,
          kind: true,
          title: true,
          execMode: true,
          requiresApproval: true,
          status: true,
          payload: true,
          result: true,
          error: true,
          executedBy: true,
          executedAt: true,
          createdAt: true,
          updatedAt: true,
          attempts: {
            select: {
              id: true,
              actorId: true,
              status: true,
              approvedPayload: true,
              result: true,
              error: true,
              attemptedAt: true,
            },
          },
        },
      },
      assets: {
        select: {
          id: true,
          kind: true,
          mimeType: true,
          bytes: true,
          filename: true,
          width: true,
          height: true,
          durationMs: true,
          source: true,
          metadata: true,
          createdAt: true,
        },
      },
      brands: {
        select: {
          id: true,
          name: true,
          websiteUrl: true,
          isPrimary: true,
          summary: true,
          audience: true,
          voice: true,
          offers: true,
          competitors: true,
          proofPoints: true,
          visualStyle: true,
          locale: true,
          timezone: true,
          currency: true,
          contextVersion: true,
          auditSnapshot: true,
          auditedAt: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      conversations: {
        select: {
          id: true,
          brandId: true,
          title: true,
          mode: true,
          status: true,
          createdBy: true,
          lastMessageAt: true,
          createdAt: true,
          updatedAt: true,
          messages: {
            select: {
              id: true,
              turnId: true,
              role: true,
              content: true,
              metadata: true,
              createdAt: true,
            },
          },
        },
      },
      integrations: {
        select: {
          id: true,
          provider: true,
          label: true,
          status: true,
          scopes: true,
          expiresAt: true,
          externalUserId: true,
          createdBy: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      channelAccounts: {
        select: {
          id: true,
          integrationId: true,
          platform: true,
          accountType: true,
          externalAccountId: true,
          displayName: true,
          status: true,
          capabilities: true,
          timezone: true,
          currency: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      contentPlans: {
        select: {
          id: true,
          brandId: true,
          name: true,
          objective: true,
          status: true,
          version: true,
          startDate: true,
          endDate: true,
          timezone: true,
          strategy: true,
          createdBy: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      contentItems: {
        select: {
          id: true,
          brandId: true,
          planId: true,
          status: true,
          source: true,
          title: true,
          brief: true,
          coreCopy: true,
          objective: true,
          metadata: true,
          version: true,
          createdBy: true,
          approvedBy: true,
          approvedAt: true,
          createdAt: true,
          updatedAt: true,
          assets: {
            select: {
              id: true,
              assetId: true,
              position: true,
              role: true,
              altText: true,
              createdAt: true,
            },
          },
        },
      },
      contentProposals: {
        select: {
          id: true,
          brandId: true,
          contentItemId: true,
          publicationId: true,
          kind: true,
          platform: true,
          format: true,
          fields: true,
          provider: true,
          model: true,
          status: true,
          createdBy: true,
          acceptedBy: true,
          acceptedAt: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      publications: {
        select: {
          id: true,
          contentItemId: true,
          channelAccountId: true,
          platform: true,
          format: true,
          status: true,
          title: true,
          body: true,
          firstComment: true,
          linkUrl: true,
          scheduledAt: true,
          publishedAt: true,
          externalId: true,
          permalink: true,
          publishAttempts: true,
          lastError: true,
          metadata: true,
          createdAt: true,
          updatedAt: true,
          attempts: {
            select: {
              id: true,
              provider: true,
              actorId: true,
              contentVersion: true,
              status: true,
              response: true,
              error: true,
              attemptedAt: true,
            },
          },
        },
      },
      seoTasks: {
        select: {
          id: true,
          brandId: true,
          fingerprint: true,
          origin: true,
          category: true,
          severity: true,
          priority: true,
          title: true,
          description: true,
          recommendedFix: true,
          status: true,
          verificationStatus: true,
          completionNote: true,
          evidence: true,
          userEdited: true,
          analyzedAt: true,
          completedAt: true,
          completedBy: true,
          createdBy: true,
          updatedBy: true,
          version: true,
          createdAt: true,
          updatedAt: true,
          proposals: {
            select: {
              id: true,
              instruction: true,
              recommendedFix: true,
              provider: true,
              model: true,
              status: true,
              createdBy: true,
              acceptedBy: true,
              acceptedAt: true,
              acceptedTaskVersion: true,
              createdAt: true,
              updatedAt: true,
            },
          },
        },
      },
      influencerProfiles: {
        select: {
          id: true,
          brandId: true,
          platform: true,
          handle: true,
          normalizedHandle: true,
          profileUrl: true,
          displayName: true,
          contactEmail: true,
          contactName: true,
          topics: true,
          audienceCountries: true,
          notes: true,
          status: true,
          source: true,
          version: true,
          createdBy: true,
          updatedBy: true,
          lastActivityAt: true,
          createdAt: true,
          updatedAt: true,
          metrics: {
            select: {
              id: true,
              metric: true,
              value: true,
              sourceUrl: true,
              observedAt: true,
              source: true,
              version: true,
              recordedBy: true,
              createdAt: true,
              updatedAt: true,
            },
          },
          outreachDrafts: {
            select: {
              id: true,
              profileVersion: true,
              subject: true,
              body: true,
              sponsorshipDisclosure: true,
              claimsRestrictions: true,
              compensationNote: true,
              status: true,
              version: true,
              createdBy: true,
              updatedBy: true,
              createdAt: true,
              updatedAt: true,
            },
          },
          trackingLinks: {
            select: {
              id: true,
              slug: true,
              destinationUrl: true,
              taggedDestinationUrl: true,
              campaignKey: true,
              enabled: true,
              clickCount: true,
              lastClickedAt: true,
              disabledAt: true,
              version: true,
              createdBy: true,
              createdAt: true,
              updatedAt: true,
            },
          },
        },
      },
    },
  });

  if (!workspace) return null;

  return {
    schemaVersion: WORKSPACE_EXPORT_SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    product: "Marpin",
    exclusions: [
      "OAuth access and refresh tokens",
      "Private object-storage keys",
      "Internal idempotency and request hashes",
    ],
    workspace,
  };
}

export function serializeWorkspaceExport(value: unknown): string {
  return JSON.stringify(
    value,
    (_key, entry) => (typeof entry === "bigint" ? entry.toString() : entry),
    2,
  );
}
