import Anthropic from "@anthropic-ai/sdk";
import { TIER_MODEL } from "./router";

/**
 * The live model call (architecture §1). Server-only — imported solely by the
 * /api/chat route. The lead prose is generated by Claude, streamed back as text
 * deltas; the model tier is chosen by the router and the stable system seed is
 * cached as a prefix. When no API key is configured the caller falls back to a
 * deterministic canned lead, so the app works with or without a key.
 */
export class MissingApiKeyError extends Error {
  constructor() {
    super("ANTHROPIC_API_KEY is not set");
    this.name = "MissingApiKeyError";
  }
}

/** True when a key is present and the live agent isn't explicitly disabled. */
export function isLiveAgentEnabled(): boolean {
  return Boolean(process.env.ANTHROPIC_API_KEY) && process.env.USE_LIVE_AGENT !== "false";
}

let client: Anthropic | null = null;
function getClient(): Anthropic {
  if (!process.env.ANTHROPIC_API_KEY) throw new MissingApiKeyError();
  if (!client) client = new Anthropic(); // resolves ANTHROPIC_API_KEY from env
  return client;
}

export async function* streamAgentText(opts: {
  model: string;
  effort: "low" | "medium" | "high";
  system: string;
  userContent: string;
  signal?: AbortSignal;
}): AsyncGenerator<string> {
  const c = getClient();

  const base = {
    model: opts.model,
    max_tokens: 1024,
    system: [
      { type: "text" as const, text: opts.system, cache_control: { type: "ephemeral" as const } },
    ],
    messages: [{ role: "user" as const, content: opts.userContent }],
  };
  // Adaptive thinking + effort apply to Sonnet/Opus; Haiku takes a plain call.
  const params =
    opts.model === TIER_MODEL.low
      ? base
      : { ...base, thinking: { type: "adaptive" as const }, output_config: { effort: opts.effort } };

  const stream = c.messages.stream(
    params as Parameters<typeof c.messages.stream>[0],
    opts.signal ? ({ signal: opts.signal } as Parameters<typeof c.messages.stream>[1]) : undefined,
  );

  for await (const event of stream) {
    if (event.type === "content_block_delta" && event.delta.type === "text_delta") {
      yield event.delta.text;
    }
  }
}
